### PR TITLE
GH29: Update to Cake.Core/Common 0.22

### LINKED ISSUE #29: Update to Cake.Core 0.22.0
To work with latest version of Cake

### PR DESCRIPTION
**Pull request by devlead**
* fixes #29

### CODE REVIEW

**Comment by gep13** [comment]
@devlead does the nuspec file not need to be updated as well?

**Comment by devlead** [comment]
yes it does I'll fix.

**Comment by devlead** [comment]
@gep13 fixed.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@devlead your changes have been merged, thanks for your contribution 👍

**Pull request merged**
